{
    "openapi": "3.0.0",
    "info": {
        "title": "Railroad API",
        "version": "1.0.0",
        "description": "API for managing users in the Railroad application"
    },
    "paths": {
        "/users": {
            "post": {
                "summary": "Create a new user",
                "tags": ["Users"],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "example": {
                                "email": "user@example.com",
                                "pseudo": "username",
                                "password": "userpassword",
                                "role": "user"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "User created successfully",
                        "content": {
                            "application/json": {
                                "example": {
                                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
                                }
                            }
                        },
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/users/{userId}": {
            "get": {
                "summary": "Get user information",
                "tags": ["Users"],
                "security": [
                    {
                        "JWT": ["admin", "employee"]
                    }
                ],
                "parameters": [
                    {
                        "name": "userId",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                    "description": "User information",
                    "content": {
                        "application/json": {
                            "example": {
                                "id": "user_id",
                                "email": "user@example.com",
                                "pseudo": "username",
                                "role": "user"
                            }
                        }
                    }
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "User not found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "put": {
            "summary": "Update user information",
            "tags": ["Users"],
            "security": [
                {
                    "JWT": ["admin", "user"]
                }
            ],
            "parameters": [
                {
                    "name": "userId",
                    "in": "path",
                    "required": true,
                    "schema": {
                        "type": "string"
                    }
                }
            ],
            "requestBody": {
                "required": true,
                "content": {
                    "application/json": {
                        "example": {
                        "email": "new_email@example.com",
                        "pseudo": "new_username",
                        "password": "new_password",
                        "role": "user"
                        }
                    }
                }
            },
            "responses": {
                "200": {
                    "description": "User updated successfully"
                },
                "403": {
                    "description": "Forbidden"
                },
                "404": {
                    "description": "User not found"
                },
                "500": {
                    "description": "Internal Server Error"
                }
            }
            },
            "delete": {
            "summary": "Delete a user",
            "tags": ["Users"],
            "parameters": [
                {
                    "name": "userId",
                    "in": "path",
                    "required": true,
                    "schema": {
                        "type": "string"
                    }
                }
            ],
            "responses": {
                "200": {
                    "description": "User deleted successfully"
                },
                "403": {
                    "description": "Forbidden"
                },
                "404": {
                    "description": "User not found"
                },
                "500": {
                    "description": "Internal Server Error"
                }
            }
            }
        },
        "/login": {
            "post": {
            "summary": "User login",
            "tags": ["Users"],
            "requestBody": {
                "required": true,
                "content": {
                "application/json": {
                    "example": {
                        "email": "user@example.com",
                        "password": "userpassword"
                    }
                }
                }
            },
            "responses": {
                "200": {
                "description": "Login successful",
                "content": {
                    "application/json": {
                        "example": {
                            "token": "jwt_token"
                        }
                    }
                }
                },
                "401": {
                    "description": "Unauthorized"
                },
                "404": {
                    "description": "User not found"
                },
                "500": {
                    "description": "Internal Server Error"
                }
            }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "JWT": {
                "type": "apiKey",
                "in": "header",
                "name": "Authorization"
            }
        }
    }
}  